version: "3"

services:

  generate-order:
    tty: true
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    image: ghcr.io/jinyoung/gpt-engineer:v5
#    command: ["-sh"]
    volumes:
      - ../order:/project
  generate-delivery:
    tty: true
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    image: ghcr.io/jinyoung/gpt-engineer:v5
#    command: ["-sh"]
    volumes:
      - ../delivery:/project
  generate-product:
    tty: true
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    image: ghcr.io/jinyoung/gpt-engineer:v5
#    command: ["-sh"]
    volumes:
      - ../product:/project
