server:
  port: 8080
---
spring:
  config:
    activate:
      on-profile: default
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        implicit_naming_strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
  cloud:
    function: 
      definition: consumer; producer
    stream:
      kafka:
        bindings:
          configuration:
            default:
              key:
                serde: org.apache.kafka.common.serialization.Serdes$StringSerde
              value:
                serde: org.apache.kafka.common.serialization.Serdes$StringSerde
        binder:
          brokers: localhost:9092                          
      bindings:
        consumer-in-0:
          group: order
          destination: mallbasic
          contentType: application/json
        producer-out-0:
          destination: mallbasic
          contentType: application/json
logging:
  level:
    org.hibernate.type: trace
    org.springframework.cloud: debug

server:
  port: 8082

---
